# .scrutinizer.yml
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    php74:
      environment:
        php: 7.4
      tests:
        override:
          - command: composer validate --strict --no-check-publish
          - command: composer update --prefer-stable --no-interaction
          - command: composer check-platform-reqs
          - command: mkdir -p build/logs
          - command: composer ci

    php80:
      environment:
        php: 8.0
      tests:
        override:
          - command: composer validate --strict --no-check-publish
          - command: composer update --prefer-stable --no-interaction
          - command: composer check-platform-reqs
          - command: mkdir -p build/logs
          - command: composer ci

    php81:
      environment:
        php: 8.1
      tests:
        override:
          - command: composer validate --strict --no-check-publish
          - command: composer update --prefer-stable --no-interaction
          - command: composer check-platform-reqs
          - command: mkdir -p build/logs
          - command: composer ci

    php82:
      environment:
        php: 8.2
      tests:
        override:
          - command: composer validate --strict --no-check-publish
          - command: composer update --prefer-stable --no-interaction
          - command: composer check-platform-reqs
          - command: mkdir -p build/logs
          - command: composer ci

    php83:
      environment:
        php: 8.3
      tests:
        override:
          - command: composer validate --strict --no-check-publish
          - command: composer update --prefer-stable --no-interaction
          - command: composer check-platform-reqs
          - command: mkdir -p build/logs
          - command: composer ci

    php84:
      environment:
        php: 8.4
      tests:
        override:
          - command: composer validate --strict --no-check-publish
          - command: composer update --prefer-stable --no-interaction
          - command: composer check-platform-reqs
          - command: mkdir -p build/logs
          - command: composer ci

filter:
  excluded_paths:
    - '_archive/*'
    - 'tests/*'
    - 'vendor/*'
    - 'docs/*'

tools:
  php_analyzer: true
